import { fromTuples } from "./_utils.mjs";

export const pairs = fromTuples([
  ["Dog", "Wolf"],
  ["Cat", "Lynx"],
  ["Eagle", "Hawk"],
  ["Bear", "Panda"],
  ["Frog", "Toad"],
  ["Lion", "Tiger"],
  ["Leopard", "Cheetah"],
  ["Jaguar", "Panther"],
  ["Hyena", "Jackal"],
  ["Fox", "Coyote"],
  ["Raccoon", "Badger"],
  ["Otter", "Beaver"],
  ["Seal", "Walrus"],
  ["Whale", "Orca"],
  ["Dolphin", "Porpoise"],
  ["Shark", "Ray"],
  ["Octopus", "Squid"],
  ["Crab", "Lobster"],
  ["Shrimp", "Prawn"],
  ["Butterfly", "Moth"],
  ["Bee", "Wasp"],
  ["Ant", "Termite"],
  ["Spider", "Scorpion"],
  ["Snake", "Lizard"],
  ["Crocodile", "Alligator"],
  ["Turtle", "Tortoise"],
  ["Chameleon", "Gecko"],
  ["Iguana", "Monitor"],
  ["Horse", "Donkey"],
  ["Zebra", "Giraffe"],
  ["Cow", "Buffalo"],
  ["Sheep", "Goat"],
  ["Pig", "Boar"],
  ["Chicken", "Rooster"],
  ["Duck", "Goose"],
  ["Turkey", "Peacock"],
  ["Owl", "Falcon"],
  ["Parrot", "Cockatoo"],
  ["Penguin", "Puffin"],
  ["Flamingo", "Stork"],
  ["Pelican", "Heron"],
  ["Crow", "Raven"],
  ["Sparrow", "Finch"],
  ["Pigeon", "Dove"],
  ["Bat", "Flying Fox"],
  ["Mouse", "Rat"],
  ["Hamster", "Gerbil"],
  ["Rabbit", "Hare"],
  ["Squirrel", "Chipmunk"],
  ["Mole", "Shrew"],
  ["Hedgehog", "Porcupine"],
  ["Kangaroo", "Wallaby"],
  ["Koala", "Wombat"],
  ["Platypus", "Echidna"],
  ["Sloth", "Anteater"],
  ["Armadillo", "Pangolin"],
  ["Monkey", "Ape"],
  ["Gorilla", "Chimpanzee"],
  ["Orangutan", "Gibbon"],
  ["Baboon", "Mandrill"],
  ["Elephant", "Mammoth"],
  ["Hippo", "Rhino"],
  ["Camel", "Llama"],
  ["Alpaca", "Vicuna"],
  ["Deer", "Elk"],
  ["Moose", "Caribou"],
  ["Antelope", "Gazelle"],
  ["Bison", "Yak"],
  ["Lynx", "Bobcat"],
  ["Cougar", "Mountain Lion"],
  ["Walrus", "Sea Lion"],
  ["Manatee", "Dugong"],
  ["Jellyfish", "Anemone"],
  ["Starfish", "Sea Urchin"],
  ["Clam", "Oyster"],
  ["Snail", "Slug"],
  ["Centipede", "Millipede"],
  ["Dragonfly", "Damselfly"],
  ["Grasshopper", "Cricket"],
  ["Beetle", "Ladybug"],
  ["Caterpillar", "Silkworm"],
  ["Mosquito", "Fly"],
  ["Flea", "Tick"],
  ["Hornet", "Yellowjacket"],
  ["Cockroach", "Beetle"],
  ["Goldfish", "Koi"],
  ["Salmon", "Trout"],
  ["Tuna", "Mackerel"],
  ["Cod", "Haddock"],
  ["Eel", "Moray"],
  ["Seahorse", "Pipefish"],
  ["Stingray", "Manta"],
  ["Barracuda", "Pike"],
  ["Catfish", "Carp"],
  ["Piranha", "Barracuda"],
  ["Angelfish", "Clownfish"],
  ["Pufferfish", "Lionfish"],
  ["Hermit Crab", "King Crab"],
  ["Sea Turtle", "Land Turtle"],
  ["Komodo Dragon", "Monitor Lizard"],
  ["Vulture", "Condor"],
  ["Ostrich", "Emu"],
  ["Cassowary", "Kiwi"],
  ["Roadrunner", "Quail"],
  ["Woodpecker", "Nuthatch"],
  ["Hummingbird", "Kingfisher"],
  ["Swan", "Crane"],
  ["Goose", "Swan"],
  ["Mallard", "Teal"],
  ["Canary", "Budgie"],
  ["Macaw", "Parakeet"],
  ["Toucan", "Hornbill"],
  ["Peacock", "Pheasant"],
  ["Rooster", "Hen"],
  ["Lamb", "Kid"],
  ["Calf", "Foal"],
  ["Puppy", "Kitten"],
  ["Colt", "Filly"],
  ["Chick", "Duckling"],
  ["Cub", "Joey"],
  ["Fawn", "Calf"],
  ["Tadpole", "Polliwog"],
  ["Caterpillar", "Larva"],
  ["Pupa", "Cocoon"],
  ["Hive", "Nest"],
  ["Den", "Burrow"],
  ["Pack", "Herd"],
  ["Flock", "School"],
  ["Pride", "Troop"],
  ["Colony", "Swarm"],
  ["Zoo", "Safari"],
  ["Aquarium", "Aviary"],
  ["Vet", "Zookeeper"],
  ["Leash", "Collar"],
  ["Kennel", "Crate"],
  ["Litter Box", "Scratching Post"],
  ["Dog Park", "Pet Store"],
  ["Wildlife", "Domestic"],
  ["Predator", "Prey"],
  ["Herbivore", "Carnivore"],
  ["Omnivore", "Scavenger"],
  ["Nocturnal", "Diurnal"],
  ["Migratory", "Resident"],
  ["Endangered", "Extinct"],
  ["Habitat", "Territory"],
  ["Camouflage", "Mimicry"],
  ["Hibernation", "Migration"],
  ["Metamorphosis", "Molting"],
  ["Antlers", "Horns"],
  ["Fur", "Feathers"],
  ["Scales", "Shell"],
  ["Whiskers", "Tail"],
  ["Paw", "Hoof"],
  ["Claw", "Talon"],
  ["Beak", "Bill"],
  ["Trunk", "Tusk"],
  ["Fin", "Flipper"],
  ["Gills", "Lungs"],
  ["Venom", "Poison"],
  ["Roar", "Growl"],
  ["Chirp", "Croak"],
  ["Howl", "Bark"],
  ["Purr", "Hiss"],
  ["Neigh", "Bray"],
  ["Oink", "Bleat"],
  ["Moo", "Baa"],
  ["Quack", "Honk"],
  ["Squeak", "Chatter"],
  ["Buzz", "Hiss"],
  ["Wild Boar", "Warthog"],
  ["Meerkat", "Mongoose"],
  ["Lemur", "Tarsier"],
  ["Tapir", "Okapi"],
  ["Narwhal", "Beluga"],
  ["Sperm Whale", "Blue Whale"],
  ["Hammerhead", "Great White"],
  ["Bull Shark", "Tiger Shark"],
  ["Electric Eel", "Knifefish"],
  ["Flying Squirrel", "Sugar Glider"],
  ["Prairie Dog", "Groundhog"],
  ["Skunk", "Stink Badger"],
  ["Weasel", "Ferret"],
  ["Mink", "Stoat"],
  ["Marten", "Fisher"],
  ["Wolverine", "Honey Badger"],
  ["Aardvark", "Anteater"],
  ["Capybara", "Guinea Pig"],
  ["Chinchilla", "Degu"],
  ["Porcupine", "Hedgehog"],
  ["Musk Ox", "Bighorn Sheep"],
  ["Ibex", "Mountain Goat"],
  ["Serval", "Caracal"],
  ["Ocelot", "Margay"],
  ["Polar Bear", "Grizzly"],
  ["Sea Otter", "River Otter"],
  ["Spinner Dolphin", "Bottlenose"],
  ["Manta Ray", "Eagle Ray"],
  ["Betta", "Guppy"],
  ["Axolotl", "Salamander"],
  ["Bullfrog", "Tree Frog"],
  ["King Cobra", "Python"],
  ["Anaconda", "Boa"],
  ["Skink", "Anole"],
]);
