import { fromTuples } from "./_utils.mjs";

export const pairs = fromTuples([
  // Japanese anime — rivals & duos
  ["Naruto", "Sasuke"],
  ["Goku", "Vegeta"],
  ["Luffy", "Zoro"],
  ["Ichigo", "Rukia"],
  ["Ash", "Pikachu"],
  ["Pikachu", "Charizard"],
  ["Sailor Moon", "Sailor Mars"],
  ["Totoro", "Catbus"],
  ["Eren", "Mikasa"],
  ["Tanjiro", "Zenitsu"],
  ["Light", "L"],
  ["Deku", "Bakugo"],
  ["Gon", "Killua"],
  ["Edward", "Alphonse"],
  ["Inuyasha", "Kagome"],
  ["Yugi", "Kaiba"],
  ["Saitama", "Genos"],
  ["Levi", "Mikasa"],
  ["Itachi", "Sasuke"],
  ["Goku", "Gohan"],
  ["Naruto", "Hinata"],
  ["Luffy", "Nami"],
  ["One Piece", "Naruto"],
  ["Dragon Ball", "One Piece"],
  ["Pokémon", "Digimon"],
  ["Attack on Titan", "Demon Slayer"],
  ["Death Note", "Code Geass"],
  ["My Hero Academia", "One Punch Man"],
  ["Bleach", "Naruto"],
  ["Sailor Moon", "Cardcaptor Sakura"],
  ["Spirited Away", "Howl's Moving Castle"],
  ["Studio Ghibli", "Disney"],
  ["Nezuko", "Tanjiro"],
  ["Rem", "Ram"],
  ["Naruto", "Boruto"],
  ["Goku", "Broly"],
  ["Vegeta", "Frieza"],
  ["Luffy", "Shanks"],
  ["Zoro", "Sanji"],
  ["Ash", "Misty"],
  ["Team Rocket", "Ash"],
  ["Jujutsu Kaisen", "Demon Slayer"],
  ["Fullmetal Alchemist", "Naruto"],
  // Western animation
  ["Mickey", "Donald"],
  ["Elsa", "Anna"],
  ["Woody", "Buzz"],
  ["Homer", "Bart"],
  ["SpongeBob", "Patrick"],
  ["Tom", "Jerry"],
  ["Shrek", "Donkey"],
  ["Simpsons", "Family Guy"],
  ["SpongeBob", "Squidward"],
  ["Batman", "Robin"],
  ["Superman", "Batman"],
  ["Aang", "Zuko"],
  ["Rick", "Morty"],
  ["Finn", "Jake"],
  ["Scooby", "Shaggy"],
  ["Bugs", "Daffy"],
  ["Minnie", "Mickey"],
  ["Cinderella", "Belle"],
  ["Nemo", "Dory"],
  ["Simba", "Mufasa"],
  ["Garfield", "Odie"],
  ["Peter", "Stewie"],
  ["Phineas", "Ferb"],
  ["Dora", "Boots"],
  ["Popeye", "Bluto"],
  ["Winnie", "Piglet"],
  ["Donald", "Goofy"],
  ["Ariel", "Ursula"],
  ["Moana", "Maui"],
  ["Mulan", "Mushu"],
  ["Toy Story", "Frozen"],
  ["Disney", "Pixar"],
  ["Cartoon Network", "Nickelodeon"],
]);
