import { fromTuples } from "./_utils.mjs";

export const pairs = fromTuples([
  ["Sushi", "Sashimi"],
  ["Burger", "Sandwich"],
  ["Chocolate", "Caramel"],
  ["Salad", "Soup"],
  ["Steak", "Ribs"],
  ["Lemonade", "Juice"],
  ["Pizza", "Calzone"],
  ["Pasta", "Risotto"],
  ["Ramen", "Udon"],
  ["Taco", "Burrito"],
  ["Nachos", "Quesadilla"],
  ["Curry", "Stew"],
  ["Falafel", "Hummus"],
  ["Bagel", "Muffin"],
  ["Croissant", "Danish"],
  ["Donut", "Cupcake"],
  ["Pie", "Tart"],
  ["Brownie", "Blondie"],
  ["Pancake", "Waffle"],
  ["Omelet", "Scramble"],
  ["Bacon", "Ham"],
  ["Sausage", "Hot Dog"],
  ["Meatball", "Patty"],
  ["Chicken", "Turkey"],
  ["Wings", "Nuggets"],
  ["Fish", "Shrimp"],
  ["Lobster", "Crab"],
  ["Oyster", "Mussel"],
  ["Caviar", "Roe"],
  ["Tuna", "Salmon"],
  ["Sardine", "Anchovy"],
  ["Pickle", "Olive"],
  ["Onion", "Garlic"],
  ["Tomato", "Pepper"],
  ["Cucumber", "Zucchini"],
  ["Carrot", "Celery"],
  ["Potato", "Sweet Potato"],
  ["Corn", "Peas"],
  ["Beans", "Lentils"],
  ["Rice", "Quinoa"],
  ["Noodles", "Vermicelli"],
  ["Bread", "Roll"],
  ["Toast", "Cracker"],
  ["Cheese", "Butter"],
  ["Cream", "Milk"],
  ["Yogurt", "Kefir"],
  ["Ice Cream", "Sorbet"],
  ["Gelato", "Frozen Yogurt"],
  ["Pudding", "Custard"],
  ["Jelly", "Jam"],
  ["Honey", "Syrup"],
  ["Sugar", "Stevia"],
  ["Salt", "Seasoning"],
  ["Pepper", "Paprika"],
  ["Basil", "Oregano"],
  ["Cinnamon", "Nutmeg"],
  ["Vanilla", "Almond"],
  ["Mint", "Licorice"],
  ["Lemon", "Lime"],
  ["Orange", "Grapefruit"],
  ["Apple", "Pear"],
  ["Peach", "Plum"],
  ["Cherry", "Berry"],
  ["Strawberry", "Raspberry"],
  ["Blueberry", "Blackberry"],
  ["Grape", "Raisin"],
  ["Watermelon", "Melon"],
  ["Pineapple", "Mango"],
  ["Banana", "Plantain"],
  ["Coconut", "Avocado"],
  ["Kiwi", "Passion Fruit"],
  ["Coffee", "Espresso"],
  ["Latte", "Cappuccino"],
  ["Tea", "Matcha"],
  ["Hot Chocolate", "Mocha"],
  ["Soda", "Sparkling Water"],
  ["Cola", "Root Beer"],
  ["Beer", "Cider"],
  ["Wine", "Champagne"],
  ["Whiskey", "Brandy"],
  ["Vodka", "Gin"],
  ["Rum", "Tequila"],
  ["Martini", "Margarita"],
  ["Mojito", "Daiquiri"],
  ["Smoothie", "Milkshake"],
  ["Water", "Coconut Water"],
  ["Broth", "Stock"],
  ["Gravy", "Sauce"],
  ["Ketchup", "Mustard"],
  ["Mayo", "Aioli"],
  ["Salsa", "Guacamole"],
  ["Dip", "Spread"],
  ["Chips", "Popcorn"],
  ["Pretzel", "Crouton"],
  ["Trail Mix", "Granola"],
  ["Cereal", "Oatmeal"],
  ["Granola Bar", "Protein Bar"],
  ["Soup", "Chowder"],
  ["Chili", "Gumbo"],
  ["Paella", "Jambalaya"],
  ["Lasagna", "Cannelloni"],
  ["Ravioli", "Gnocchi"],
  ["Dumpling", "Wonton"],
  ["Spring Roll", "Egg Roll"],
  ["Samosa", "Pakora"],
  ["Kebab", "Shawarma"],
  ["Gyros", "Souvlaki"],
  ["Pho", "Banh Mi"],
  ["Pad Thai", "Fried Rice"],
  ["Teriyaki", "Tempura"],
  ["Kimchi", "Sauerkraut"],
  ["Coleslaw", "Slaw"],
  ["Caesar", "Cobb"],
  ["Greek Salad", "Caprese"],
  ["Bruschetta", "Crostini"],
  ["Fondue", "Raclette"],
  ["Charcuterie", "Antipasto"],
  ["Buffet", "Banquet"],
  ["Lunch", "Dinner"],
  ["Appetizer", "Entree"],
  ["Dessert", "Pastry"],
  ["Candy", "Gummy"],
  ["Lollipop", "Gum"],
  ["Cookie", "Biscuit"],
  ["Macaron", "Eclair"],
  ["Tiramisu", "Cheesecake"],
  ["Cannoli", "Baklava"],
  ["Crepe", "Crepe Suzette"],
  ["Fudge", "Toffee"],
  ["Truffle", "Praline"],
  ["Marshmallow", "Meringue"],
  ["Whipped Cream", "Frosting"],
  ["Vegan", "Vegetarian"],
  ["Spicy", "Mild"],
  ["Sweet", "Savory"],
  ["Fried", "Baked"],
  ["Fresh", "Frozen"],
  ["Bakery", "Deli"],
  ["Takeout", "Delivery"],
  ["Picnic", "Potluck"],
  ["Food Truck", "Food Cart"],
  ["Dim Sum", "Hot Pot"],
  ["Tapas", "Meze"],
  ["Tofu", "Tempeh"],
  ["Soy Sauce", "Tamari"],
  ["Hot Sauce", "Sriracha"],
  ["Olive Oil", "Vegetable Oil"],
  ["Flour", "Cornmeal"],
  ["Marinade", "Brine"],
  ["Prosciutto", "Salami"],
  ["Calamari", "Octopus"],
  ["Gazpacho", "Bisque"],
  ["Clam", "Mussel"],
  ["Scallop", "Abalone"],
  ["Halibut", "Cod"],
  ["Trout", "Bass"],
  ["Duck", "Goose"],
  ["Lamb", "Mutton"],
  ["Venison", "Bison"],
  ["Quail", "Pheasant"],
  ["Egg", "Quail Egg"],
  ["Yolk", "White"],
  ["Scrambled", "Poached"],
  ["Hard Boiled", "Soft Boiled"],
  ["Frittata", "Quiche"],
  ["Baguette", "Ciabatta"],
  ["Sourdough", "Rye"],
  ["Pita", "Naan"],
  ["Tortilla", "Wrap"],
  ["Polenta", "Grits"],
  ["Couscous", "Bulgur"],
  ["Barley", "Millet"],
  ["Chickpea", "Fava Bean"],
  ["Edamame", "Snap Pea"],
  ["Artichoke", "Asparagus"],
  ["Beet", "Radish"],
  ["Turnip", "Parsnip"],
  ["Leek", "Shallot"],
  ["Kale", "Spinach"],
  ["Arugula", "Lettuce"],
  ["Endive", "Escarole"],
  ["Fennel", "Dill"],
  ["Cilantro", "Parsley"],
  ["Thyme", "Rosemary"],
  ["Sage", "Bay Leaf"],
  ["Cardamom", "Clove"],
  ["Ginger", "Turmeric"],
  ["Chili", "Jalapeno"],
  ["Habanero", "Serrano"],
  ["Maple", "Agave"],
  ["Molasses", "Treacle"],
  ["Cocoa", "Cacao"],
  ["Espresso Bean", "Coffee Bean"],
  ["Chai", "Chamomile"],
  ["Iced Tea", "Sweet Tea"],
  ["Slushie", "Slurpee"],
  ["Punch", "Sangria"],
  ["Mulled Wine", "Glühwein"],
  ["Eggnog", "Hot Toddy"],
  ["Sake", "Soju"],
  ["Mezcal", "Pulque"],
]);
