import { fromTuples } from "./_utils.mjs";

export const pairs = fromTuples([
  ["Rock", "Pop"],
  ["Jazz", "Blues"],
  ["Hip Hop", "Rap"],
  ["Country", "Folk"],
  ["Classical", "Opera"],
  ["Metal", "Punk"],
  ["Reggae", "Ska"],
  ["Guitar", "Piano"],
  ["Drums", "Violin"],
  ["Bass", "Guitar"],
  ["Trumpet", "Saxophone"],
  ["Flute", "Clarinet"],
  ["Microphone", "Speaker"],
  ["Concert", "Festival"],
  ["Album", "Single"],
  ["Beatles", "Rolling Stones"],
  ["Elvis", "Beatles"],
  ["Michael Jackson", "Prince"],
  ["Madonna", "Lady Gaga"],
  ["Beyoncé", "Rihanna"],
  ["Drake", "Kanye"],
  ["Eminem", "Jay-Z"],
  ["Taylor Swift", "Adele"],
  ["Ed Sheeran", "Bruno Mars"],
  ["Queen", "AC/DC"],
  ["Pink Floyd", "Led Zeppelin"],
  ["Nirvana", "Pearl Jam"],
  ["Metallica", "Iron Maiden"],
  ["U2", "Coldplay"],
  ["Radiohead", "Oasis"],
  ["Bob Marley", "Bob Dylan"],
  ["Frank Sinatra", "Elvis"],
  ["Whitney Houston", "Mariah Carey"],
  ["Ariana Grande", "Billie Eilish"],
  ["Justin Bieber", "Shawn Mendes"],
  ["Post Malone", "Travis Scott"],
  ["Kendrick Lamar", "Drake"],
  ["Snoop Dogg", "Dr Dre"],
  ["Tupac", "Biggie"],
  ["Mozart", "Beethoven"],
  ["Bach", "Mozart"],
  ["Vivaldi", "Bach"],
  ["Chopin", "Liszt"],
  ["Opera", "Ballet"],
  ["Orchestra", "Band"],
  ["Choir", "Orchestra"],
  ["DJ", "Producer"],
  ["Vinyl", "CD"],
  ["Spotify", "Apple Music"],
  ["YouTube", "TikTok"],
  ["Karaoke", "Concert"],
  ["Grammy", "Oscar"],
  ["Billboard", "Grammy"],
  ["Woodstock", "Coachella"],
  ["Glastonbury", "Coachella"],
  ["Rock", "Metal"],
  ["Pop", "Dance"],
  ["EDM", "House"],
  ["Techno", "House"],
  ["Disco", "Funk"],
  ["Soul", "R&B"],
  ["Gospel", "Soul"],
  ["Blues", "Rock"],
  ["Banjo", "Ukulele"],
  ["Harmonica", "Accordion"],
  ["Cello", "Violin"],
  ["Harp", "Piano"],
  ["Synthesizer", "Piano"],
  ["Electric Guitar", "Acoustic Guitar"],
  ["Amplifier", "Microphone"],
  ["Studio", "Stage"],
  ["Composer", "Lyricist"],
  ["Singer", "Rapper"],
  ["Band", "Solo Artist"],
  ["Boy Band", "Girl Group"],
  ["One Direction", "BTS"],
  ["BTS", "Blackpink"],
  ["ABBA", "Bee Gees"],
  ["Spice Girls", "Destiny's Child"],
  ["Backstreet Boys", "NSYNC"],
  ["Elton John", "Freddie Mercury"],
  ["David Bowie", "Elton John"],
  ["Stevie Wonder", "Ray Charles"],
  ["Aretha Franklin", "Nina Simone"],
  ["Bob Dylan", "Neil Young"],
  ["Johnny Cash", "Willie Nelson"],
  ["Dolly Parton", "Shania Twain"],
  ["Garth Brooks", "Tim McGraw"],
  ["Shakira", "Jennifer Lopez"],
  ["Enrique Iglesias", "Ricky Martin"],
  ["Pitbull", "Enrique Iglesias"],
  ["Bad Bunny", "J Balvin"],
  ["Rosalía", "Shakira"],
  ["Daft Punk", "Deadmau5"],
  ["Skrillex", "Calvin Harris"],
  ["Avicii", "David Guetta"],
  ["Marshmello", "The Chainsmokers"],
  ["Linkin Park", "Green Day"],
  ["Red Hot Chili Peppers", "Foo Fighters"],
  ["Arctic Monkeys", "The Strokes"],
  ["Imagine Dragons", "Twenty One Pilots"],
  ["Maroon 5", "OneRepublic"],
  ["The Weeknd", "Bruno Mars"],
  ["Sam Smith", "Lewis Capaldi"],
  ["Adele", "Sam Smith"],
  ["Alicia Keys", "John Legend"],
  ["Pharrell", "Kanye"],
  ["Lil Wayne", "Nicki Minaj"],
  ["Cardi B", "Nicki Minaj"],
  ["Dua Lipa", "Doja Cat"],
  ["Harry Styles", "Zayn Malik"],
  ["OneRepublic", "Coldplay"],
  ["Bon Jovi", "Aerosmith"],
  ["Guns N Roses", "Aerosmith"],
  ["Scorpions", "Bon Jovi"],
  ["Europe", "Scorpions"],
]);
