import { fromTuples } from "./_utils.mjs";

export const pairs = fromTuples([
  ["Star Wars", "Star Trek"],
  ["Batman", "Superman"],
  ["Marvel", "DC"],
  ["Harry Potter", "Lord of the Rings"],
  ["Friends", "Seinfeld"],
  ["Game of Thrones", "House of the Dragon"],
  ["Breaking Bad", "Better Call Saul"],
  ["The Office", "Parks and Recreation"],
  ["Stranger Things", "Dark"],
  ["James Bond", "Mission Impossible"],
  ["Indiana Jones", "Tomb Raider"],
  ["Jurassic Park", "King Kong"],
  ["Titanic", "Avatar"],
  ["Forrest Gump", "Cast Away"],
  ["The Godfather", "Scarface"],
  ["Pulp Fiction", "Reservoir Dogs"],
  ["Inception", "Interstellar"],
  ["The Matrix", "Blade Runner"],
  ["Jaws", "Alien"],
  ["Rocky", "Rambo"],
  ["Terminator", "RoboCop"],
  ["Back to the Future", "Ghostbusters"],
  ["Home Alone", "Die Hard"],
  ["Shrek", "Monsters Inc"],
  ["Frozen", "Moana"],
  ["The Lion King", "Tarzan"],
  ["Finding Nemo", "Finding Dory"],
  ["Toy Story", "Cars"],
  ["Spider-Man", "Iron Man"],
  ["Captain America", "Thor"],
  ["Avengers", "Justice League"],
  ["X-Men", "Fantastic Four"],
  ["Fast and Furious", "Need for Speed"],
  ["Transformers", "Pacific Rim"],
  ["Pirates of the Caribbean", "Treasure Island"],
  ["Twilight", "Hunger Games"],
  ["Lord of the Rings", "The Hobbit"],
  ["Sherlock Holmes", "Hercule Poirot"],
  ["Doctor Who", "Star Trek"],
  ["Grey's Anatomy", "House"],
  ["Lost", "Survivor"],
  ["The Simpsons Movie", "South Park"],
  ["Joker", "Batman"],
  ["Gladiator", "Braveheart"],
  ["Titanic", "The Notebook"],
  ["La La Land", "Greatest Showman"],
  ["Oppenheimer", "Barbie"],
  ["Dune", "Star Wars"],
  ["Top Gun", "Top Gun Maverick"],
  ["Black Panther", "Wonder Woman"],
  ["Deadpool", "Wolverine"],
  ["Men in Black", "Ghostbusters"],
  ["The Walking Dead", "Fear the Walking Dead"],
  ["Squid Game", "Alice in Borderland"],
  ["Wednesday", "Addams Family"],
  ["Peaky Blinders", "Boardwalk Empire"],
  ["Money Heist", "Ocean's Eleven"],
  ["The Crown", "Downton Abbey"],
  ["Bridgerton", "Gossip Girl"],
  ["Euphoria", "Skins"],
  ["Westworld", "Black Mirror"],
  ["True Detective", "Mindhunter"],
  ["Narcos", "Breaking Bad"],
  ["The Witcher", "Game of Thrones"],
  ["Vikings", "Game of Thrones"],
  ["Casino", "Goodfellas"],
  ["Scarface", "Carlito's Way"],
  ["The Shawshank Redemption", "The Green Mile"],
  ["Fight Club", "American Psycho"],
  ["The Dark Knight", "Batman Begins"],
  ["Iron Man", "Captain America"],
  ["Guardians of the Galaxy", "Thor"],
  ["Ant-Man", "Wasp"],
  ["Doctor Strange", "Scarlet Witch"],
  ["Black Widow", "Hawkeye"],
  ["Loki", "Thor"],
  ["WandaVision", "Agatha"],
  ["Mandalorian", "Boba Fett"],
  ["Obi-Wan", "Anakin"],
  ["Luke Skywalker", "Darth Vader"],
  ["Han Solo", "Chewbacca"],
  ["Yoda", "Obi-Wan"],
  ["Frodo", "Sam"],
  ["Gandalf", "Dumbledore"],
  ["Hermione", "Ron"],
  ["Snape", "Dumbledore"],
  ["Voldemort", "Sauron"],
  ["Gollum", "Yoda"],
  ["Legolas", "Aragorn"],
  ["Gimli", "Legolas"],
  ["Neo", "Morpheus"],
  ["Trinity", "Neo"],
  ["Agent Smith", "Neo"],
  ["John Wick", "Jason Bourne"],
  ["Taken", "John Wick"],
  ["Mad Max", "Blade Runner"],
  ["Alien", "Predator"],
  ["King Kong", "Godzilla"],
  ["Godzilla", "Mothra"],
  ["Jurassic World", "Jurassic Park"],
  ["ET", "Close Encounters"],
  ["Cast Away", "Robinson Crusoe"],
  ["Cast Away", "Forrest Gump"],
]);
