import { fromTuples } from "./_utils.mjs";

export const pairs = fromTuples([
  ["Paris", "London"],
  ["Museum", "Gallery"],
  ["Hotel", "Hostel"],
  ["Forest", "Park"],
  ["Airport", "Station"],
  ["Library", "Bookstore"],
  ["Rome", "Athens"],
  ["Berlin", "Vienna"],
  ["Madrid", "Lisbon"],
  ["Amsterdam", "Brussels"],
  ["Prague", "Budapest"],
  ["Dublin", "Edinburgh"],
  ["Stockholm", "Oslo"],
  ["Milan", "Turin"],
  ["Barcelona", "Valencia"],
  ["Naples", "Florence"],
  ["Venice", "Verona"],
  ["New York", "Chicago"],
  ["Los Angeles", "San Francisco"],
  ["Miami", "Orlando"],
  ["Boston", "Philadelphia"],
  ["Seattle", "Portland"],
  ["Toronto", "Montreal"],
  ["Mexico City", "Guadalajara"],
  ["Buenos Aires", "Santiago"],
  ["Rio", "Sao Paulo"],
  ["Cairo", "Marrakech"],
  ["Dubai", "Abu Dhabi"],
  ["Istanbul", "Ankara"],
  ["Tokyo", "Osaka"],
  ["Seoul", "Busan"],
  ["Beijing", "Shanghai"],
  ["Bangkok", "Singapore"],
  ["Sydney", "Melbourne"],
  ["Mumbai", "Delhi"],
  ["School", "University"],
  ["Hospital", "Clinic"],
  ["Bank", "ATM"],
  ["Office", "Coworking Space"],
  ["Factory", "Warehouse"],
  ["Farm", "Ranch"],
  ["Market", "Mall"],
  ["Restaurant", "Cafe"],
  ["Bar", "Pub"],
  ["Theater", "Cinema"],
  ["Stadium", "Arena"],
  ["Zoo", "Aquarium"],
  ["Castle", "Palace"],
  ["Cathedral", "Chapel"],
  ["Temple", "Shrine"],
  ["Mosque", "Synagogue"],
  ["Cemetery", "Memorial"],
  ["Bridge", "Tunnel"],
  ["Harbor", "Marina"],
  ["Port", "Dock"],
  ["Beach", "Resort"],
  ["Island", "Coast"],
  ["Mountain", "Valley"],
  ["Desert", "Oasis"],
  ["Lake", "River"],
  ["Waterfall", "Spring"],
  ["Cave", "Grotto"],
  ["Village", "Town"],
  ["City", "Capital"],
  ["Embassy", "Consulate"],
  ["Courthouse", "City Hall"],
  ["Police Station", "Fire Station"],
  ["Prison", "Jail"],
  ["Bus Stop", "Train Station"],
  ["Subway", "Tram"],
  ["Parking Lot", "Garage"],
  ["Highway", "Freeway"],
  ["Plaza", "Square"],
  ["Avenue", "Boulevard"],
  ["Kitchen", "Dining Room"],
  ["Bedroom", "Living Room"],
  ["Bathroom", "Laundry Room"],
  ["Attic", "Basement"],
  ["Lobby", "Hallway"],
  ["Apartment", "Condo"],
  ["Cottage", "Cabin"],
  ["Mansion", "Villa"],
  ["Inn", "Motel"],
  ["Resort", "Lodge"],
  ["Theme Park", "Amusement Park"],
  ["Convention Center", "Expo Hall"],
  ["Laboratory", "Research Center"],
  ["Observatory", "Planetarium"],
  ["Mine", "Quarry"],
  ["Power Plant", "Substation"],
  ["Dam", "Reservoir"],
  ["Skyscraper", "High-Rise"],
  ["Boutique", "Department Store"],
  ["Salon", "Barbershop"],
  ["Gym", "Fitness Center"],
  ["Golf Course", "Country Club"],
  ["Ice Rink", "Bowling Alley"],
  ["National Park", "State Park"],
  ["Peninsula", "Cape"],
  ["Bay", "Gulf"],
  ["Old Town", "Downtown"],
  ["Chinatown", "Little Italy"],
  ["Gas Station", "Charging Station"],
  ["Post Office", "Courier Hub"],
  ["Data Center", "Server Farm"],
  ["Baggage Claim", "Security Line"],
  ["Runway", "Hangar"],
  ["Ferry Dock", "Cruise Terminal"],
  ["Parliament", "Congress"],
  ["TV Studio", "Radio Station"],
  ["Science Lab", "Computer Lab"],
  ["ER", "Urgent Care"],
  ["Vet Clinic", "Animal Hospital"],
  ["Barn", "Stable"],
  ["Greenhouse", "Garden Center"],
  ["Metro Stop", "Bus Terminal"],
  ["Ski Resort", "Mountain Lodge"],
  ["Tourist Office", "Welcome Center"],
  ["Pyramid", "Temple"],
  ["Colosseum", "Forum"],
  ["Eiffel Tower", "Big Ben"],
  ["Great Wall", "Forbidden City"],
  ["Taj Mahal", "Red Fort"],
  ["Stonehenge", "Hadrian's Wall"],
  ["Louvre", "Hermitage"],
  ["Broadway", "West End"],
  ["Wall Street", "City of London"],
  ["Times Square", "Piccadilly Circus"],
  ["Central Park", "Hyde Park"],
  ["Grand Canyon", "Death Valley"],
  ["Niagara Falls", "Victoria Falls"],
  ["Mount Everest", "K2"],
  ["Alps", "Pyrenees"],
  ["Sahara", "Gobi"],
  ["Amazon", "Congo"],
  ["Thames", "Seine"],
  ["Mediterranean", "Caribbean"],
  ["Pacific", "Atlantic"],
  ["Hawaii", "Bahamas"],
  ["Santorini", "Mykonos"],
  ["Ibiza", "Majorca"],
  ["Cannes", "Nice"],
  ["Monaco", "Monte Carlo"],
  ["Las Vegas", "Atlantic City"],
  ["Disneyland", "Universal Studios"],
  ["Oktoberfest", "Carnival"],
  ["Flea Market", "Farmers Market"],
  ["Outlet Mall", "Shopping Center"],
  ["Campsite", "RV Park"],
  ["Hiking Trail", "Bike Path"],
  ["Wildlife Reserve", "Bird Sanctuary"],
  ["Ghost Town", "Historic District"],
  ["Waterfront", "Harborfront"],
  ["Financial District", "Arts District"],
  ["Border Crossing", "Checkpoint"],
  ["Stock Exchange", "Trading Floor"],
  ["White House", "Kremlin"],
  ["Buckingham Palace", "Versailles"],
  ["Space Center", "Launch Pad"],
  ["Botanical Garden", "Arboretum"],
  ["Vineyard", "Winery"],
  ["Brewery", "Distillery"],
  ["Food Hall", "Night Market"],
  ["Rooftop Bar", "Speakeasy"],
  ["Dog Park", "Dog Beach"],
  ["Water Park", "Splash Pad"],
  ["Coral Reef", "Diving Spot"],
  ["Public Pool", "Lap Pool"],
  ["Onsen", "Public Bath"],
  ["Currency Exchange", "Travel Agency"],
  ["Concierge", "Reception"],
  ["Penthouse", "Junior Suite"],
  ["Fire Escape", "Emergency Exit"],
  ["Marina Berth", "Boat Ramp"],
  ["Lighthouse", "Foghorn Station"],
  ["Solar Farm", "Wind Farm"],
  ["Alpine Hut", "Mountain Refuge"],
  ["Ice Hotel", "Glass Igloo"],
  ["Capsule Hotel", "Pod Stay"],
  ["Casino", "Poker Room"],
  ["Comic Con", "Game Expo"],
  ["Wedding Chapel", "Registry Office"],
  ["Banquet Hall", "Reception Venue"],
  ["Funeral Home", "Crematorium"],
  ["Memorial Wall", "War Monument"],
  ["Driving School", "Flight School"],
  ["Dive Center", "Surf School"],
  ["Farm Stay", "Agriturismo"],
  ["Rice Terrace", "Tea Plantation"],
  ["Cliff Walk", "Coastal Path"],
  ["Boardwalk", "Promenade"],
  ["Pier", "Wharf"],
  ["Cable Car", "Funicular"],
  ["Helipad", "Seaplane Dock"],
  ["Duty Free", "Travel Store"],
  ["Gate", "Terminal"],
  ["Control Tower", "Radar Station"],
  ["Cargo Terminal", "Freight Yard"],
  ["Naval Base", "Air Base"],
  ["Bank Vault", "Safety Deposit"],
]);
