import { fromTuples } from "./_utils.mjs";

export const pairs = fromTuples([
  // Anime giapponese
  ["Naruto", "Sasuke"],
  ["Goku", "Vegeta"],
  ["Luffy", "Rorono"],
  ["Ash", "Pikachu"],
  ["Pikachu", "Charizard"],
  ["Sailor Moon", "Sailor Mars"],
  ["Totoro", "Gatto Bus"],
  ["Eren", "Mikasa"],
  ["Tanjiro", "Zenitsu"],
  ["Light", "L"],
  ["Deku", "Bakugo"],
  ["Gon", "Killua"],
  ["Edward", "Alphonse"],
  ["Inuyasha", "Kagome"],
  ["Yugi", "Kaiba"],
  ["Saitama", "Genos"],
  ["Levi", "Mikasa"],
  ["Itachi", "Sasuke"],
  ["Goku", "Gohan"],
  ["Naruto", "Hinata"],
  ["Luffy", "Nami"],
  ["One Piece", "Naruto"],
  ["Dragon Ball", "One Piece"],
  ["Pokémon", "Digimon"],
  ["L'Attacco dei Giganti", "Demon Slayer"],
  ["Death Note", "Code Geass"],
  ["My Hero Academia", "One Punch Man"],
  ["Bleach", "Naruto"],
  ["Sailor Moon", "Card Captor Sakura"],
  ["La Città Incantata", "Il Castello Errante"],
  ["Studio Ghibli", "Disney"],
  ["Nezuko", "Tanjiro"],
  ["Rem", "Ram"],
  ["Naruto", "Boruto"],
  ["Goku", "Broly"],
  ["Vegeta", "Freezer"],
  ["Luffy", "Shanks"],
  ["Zoro", "Sanji"],
  ["Ash", "Misty"],
  ["Team Rocket", "Ash"],
  ["Jujutsu Kaisen", "Demon Slayer"],
  ["Fullmetal Alchemist", "Naruto"],
  // Cartoni occidentali
  ["Topolino", "Paperino"],
  ["Elsa", "Anna"],
  ["Woody", "Buzz"],
  ["Homer", "Bart"],
  ["SpongeBob", "Patrick"],
  ["Tom", "Jerry"],
  ["Shrek", "Asino"],
  ["I Simpson", "I Griffin"],
  ["SpongeBob", "Squiddi"],
  ["Batman", "Robin"],
  ["Superman", "Batman"],
  ["Aang", "Zuko"],
  ["Rick", "Morty"],
  ["Finn", "Jake"],
  ["Scooby", "Shaggy"],
  ["Bugs", "Daffy"],
  ["Minnie", "Topolino"],
  ["Cenerentola", "Belle"],
  ["Nemo", "Dory"],
  ["Simba", "Mufasa"],
  ["Garfield", "Odie"],
  ["Peter", "Stewie"],
  ["Phineas", "Ferb"],
  ["Dora", "Boots"],
  ["Braccio di Ferro", "Bruto"],
  ["Winnie", "Tigro"],
  ["Paperino", "Pippo"],
  ["Ariel", "Ursula"],
  ["Oceania", "Vaiana"],
  ["Mulan", "Mushu"],
  ["Toy Story", "Frozen"],
  ["Disney", "Pixar"],
  ["Cartoon Network", "Nickelodeon"],
]);
