import { fromTuples } from "./_utils.mjs";

export const pairs = fromTuples([
  ["Cane", "Lupo"],
  ["Gatto", "Lince"],
  ["Aquila", "Falco"],
  ["Squalo", "Delfino"],
  ["Orso", "Panda"],
  ["Rana", "Rospo"],
  ["Leone", "Tigre"],
  ["Leopardo", "Ghepardo"],
  ["Giaguaro", "Pantera"],
  ["Iena", "Sciacallo"],
  ["Volpe", "Coyote"],
  ["Procione", "Tasso"],
  ["Lontra", "Castoro"],
  ["Foca", "Tricheco"],
  ["Balena", "Orca"],
  ["Delfino", "Tursiope"],
  ["Squalo", "Razza"],
  ["Polpo", "Calamaro"],
  ["Granchio", "Aragosta"],
  ["Gambero", "Gamberetto"],
  ["Farfalla", "Falena"],
  ["Ape", "Vespa"],
  ["Formica", "Termite"],
  ["Ragno", "Scorpione"],
  ["Serpente", "Lucertola"],
  ["Coccodrillo", "Alligatore"],
  ["Tartaruga", "Testuggine"],
  ["Camaleonte", "Geco"],
  ["Iguana", "Varano"],
  ["Cavallo", "Asino"],
  ["Zebra", "Giraffa"],
  ["Mucca", "Bufalo"],
  ["Pecora", "Capra"],
  ["Maiale", "Cinghiale"],
  ["Gallina", "Gallo"],
  ["Anatra", "Oca"],
  ["Tacchino", "Pavone"],
  ["Gufo", "Falco"],
  ["Pappagallo", "Cacatua"],
  ["Pinguino", "Pulcinella di mare"],
  ["Fenicottero", "Cicogna"],
  ["Pellicano", "Airone"],
  ["Corvo", "Cornacchia"],
  ["Passero", "Fringuello"],
  ["Piccione", "Colomba"],
  ["Pipistrello", "Volpe volante"],
  ["Topo", "Ratto"],
  ["Criceto", "Gerbillo"],
  ["Coniglio", "Lepre"],
  ["Scoiattolo", "Chipmunk"],
  ["Talpa", "Toporagno"],
  ["Riccio", "Istrice"],
  ["Canguro", "Wallaby"],
  ["Koala", "Wombat"],
  ["Ornitorinco", "Echidna"],
  ["Bradipo", "Formichiere"],
  ["Armadillo", "Pangolino"],
  ["Scimmia", "Scimpanzé"],
  ["Gorilla", "Bonobo"],
  ["Orango", "Gibbone"],
  ["Babbuino", "Mandrillo"],
  ["Elefante", "Mammut"],
  ["Ippopotamo", "Rinoceronte"],
  ["Cammello", "Lama"],
  ["Alpaca", "Vicuña"],
  ["Cervo", "Alce"],
  ["Alce", "Caribù"],
  ["Antilope", "Gazzella"],
  ["Bisonte", "Yak"],
  ["Lince", "Gatto selvatico"],
  ["Puma", "Leone di montagna"],
  ["Tricheco", "Leone marino"],
  ["Manatee", "Dugongo"],
  ["Medusa", "Anemone"],
  ["Stella marina", "Riccio di mare"],
  ["Vongola", "Ostrica"],
  ["Lumaca", "Lumaca di terra"],
  ["Millepiedi", "Centopiedi"],
  ["Libellula", "Damigella"],
  ["Cavalletta", "Grillo"],
  ["Scarafaggio", "Scarabeo"],
  ["Coccinella", "Scarabeo"],
  ["Mosca", "Zanzara"],
  ["Pulce", "Zecca"],
  ["Calabrone", "Vespa"],
  ["Pesce rosso", "Carpa koi"],
  ["Salmone", "Trota"],
  ["Tonno", "Sgombro"],
  ["Merluzzo", "Nasello"],
  ["Anguilla", "Murena"],
  ["Cavalluccio marino", "Pesce pipa"],
  ["Razza", "Manta"],
  ["Pesce palla", "Pesce leone"],
  ["Granchio eremita", "Granchio reale"],
  ["Tartaruga marina", "Tartaruga di terra"],
  ["Drago di Komodo", "Varano"],
  ["Avvoltoio", "Condor"],
  ["Struzzo", "Emù"],
  ["Casuario", "Kiwi"],
  ["Picchio", "Cincia"],
  ["Colibrì", "Martin pescatore"],
  ["Cigno", "Gru"],
  ["Anatra selvatica", "Alzavola"],
  ["Canarino", "Parrocchetto"],
  ["Ara", "Pappagallino"],
  ["Tucano", "Bucero"],
  ["Pavone", "Fagiano"],
  ["Gallo", "Gallina"],
  ["Agnello", "Capretto"],
  ["Vitello", "Puledro"],
  ["Cucciolo", "Gattino"],
  ["Puledro", "Puledra"],
  ["Pulcino", "Anatroccolo"],
  ["Cucciolo", "Piccolo canguro"],
  ["Cerfetto", "Vitello"],
  ["Girino", "Larvetta"],
  ["Bruco", "Larva"],
  ["Bozzolo", "Crisalide"],
  ["Alveare", "Nido"],
  ["Tana", "Tana"],
  ["Branco", "Mandria"],
  ["Stormo", "Banco"],
  ["Branco", "Truppa"],
  ["Colonia", "Sciame"],
  ["Zoo", "Safari"],
  ["Acquario", "Voliera"],
  ["Veterinario", "Guardiano dello zoo"],
  ["Guinzaglio", "Collare"],
  ["Cuccia", "Trasportino"],
  ["Lettiera", "Tiragraffi"],
  ["Area cani", "Negozio di animali"],
  ["Selvatico", "Domestico"],
  ["Predatore", "Preda"],
  ["Erbivoro", "Carnivoro"],
  ["Onnivoro", "Spazzino"],
  ["Notturno", "Diurno"],
  ["Migratorio", "Stanziale"],
  ["In pericolo", "Estinto"],
  ["Habitat", "Territorio"],
  ["Mimetismo", "Camuffamento"],
  ["Ibernazione", "Migrazione"],
  ["Metamorfosi", "Muta"],
  ["Corna", "Zanne"],
  ["Pelliccia", "Piume"],
  ["Scaglie", "Guscio"],
  ["Baffi", "Coda"],
  ["Zampa", "Zoccolo"],
  ["Artiglio", "Artiglio"],
  ["Becco", "Rostro"],
  ["Proboscide", "Zanna"],
  ["Pinna", "Pinna"],
  ["Branchie", "Polmoni"],
  ["Veleno", "Tossina"],
  ["Ruggito", "Ringhio"],
  ["Cinguettio", "Gracidio"],
  ["Ululato", "Abbaiare"],
  ["Fusa", "Sibilo"],
  ["Nitrito", "Raglio"],
  ["Grugnito", "Belato"],
  ["Muggito", "Belato"],
  ["Qua qua", "Starnazzo"],
  ["Squittio", "Chiacchierio"],
  ["Ronzio", "Sibilo"],
  ["Cinghiale", "Facocero"],
  ["Suricata", "Mangusta"],
  ["Lemure", "Tarsio"],
  ["Tapiro", "Okapi"],
  ["Narvalo", "Beluga"],
  ["Capodoglio", "Balenottera azzurra"],
  ["Squalo martello", "Grande squalo bianco"],
  ["Anguilla elettrica", "Pesce coltello"],
  ["Scoiattolo volante", "Petauro dello zucchero"],
  ["Marmotta", "Castoro"],
  ["Puzzola", "Tasso"],
  ["Donnola", "Furetto"],
  ["Visone", "Ermellino"],
  ["Martora", "Pesca"],
  ["Ghiottone", "Tasso del miele"],
  ["Porcupine", "Riccio"],
  ["Muflone", "Stambecco"],
  ["Gazzella", "Impala"],
  ["Gnu", "Antilope"],
  ["Serval", "Caracal"],
  ["Ocelot", "Margay"],
  ["Orso polare", "Orso grizzly"],
  ["Lontra marina", "Lontra di fiume"],
  ["Delfino tursiope", "Delfino dal naso a bottiglia"],
  ["Manta", "Razza aquila"],
  ["Pesce betta", "Pesce guppy"],
  ["Assolotto", "Salamandra"],
  ["Rospo comune", "Raganella"],
  ["Cobra reale", "Pitone"],
  ["Serpente a sonagli", "Vipera"],
  ["Serpente giarrettiera", "Serpente del grano"],
  ["Anaconda", "Boa"],
  ["Gila monster", "Varano"],
  ["Lucertola con collare", "Basilisco"],
  ["Skink", "Anole"],
  ["Cavallo marino", "Pesce cavalluccio"],
  ["Rana toro", "Raganella"],
]);
