import { fromTuples } from "./_utils.mjs";

export const pairs = fromTuples([
  ["Sushi", "Sashimi"],
  ["Hamburger", "Panino"],
  ["Cioccolato", "Caramello"],
  ["Insalata", "Zuppa"],
  ["Bistecca", "Costine"],
  ["Limonata", "Succo"],
  ["Pizza", "Calzone"],
  ["Pasta", "Risotto"],
  ["Ramen", "Udon"],
  ["Taco", "Burrito"],
  ["Nachos", "Quesadilla"],
  ["Curry", "Stufato"],
  ["Falafel", "Hummus"],
  ["Bagel", "Muffin"],
  ["Cornetto", "Brioche"],
  ["Ciambella", "Cupcake"],
  ["Torta", "Crostata"],
  ["Brownie", "Blondie"],
  ["Pancake", "Waffle"],
  ["Frittata", "Strapazzata"],
  ["Pancetta", "Prosciutto"],
  ["Salsiccia", "Wurstel"],
  ["Polpetta", "Hamburger"],
  ["Pollo", "Tacchino"],
  ["Ali di pollo", "Nuggets"],
  ["Pesce", "Gambero"],
  ["Aragosta", "Granchio"],
  ["Ostrica", "Cozza"],
  ["Caviale", "Uova di pesce"],
  ["Tonno", "Salmone"],
  ["Sardina", "Acciuga"],
  ["Sottaceto", "Oliva"],
  ["Cipolla", "Aglio"],
  ["Pomodoro", "Peperone"],
  ["Cetriolo", "Zucchina"],
  ["Carota", "Sedano"],
  ["Patata", "Patata dolce"],
  ["Mais", "Piselli"],
  ["Fagioli", "Lenticchie"],
  ["Riso", "Quinoa"],
  ["Tagliatelle", "Vermicelli"],
  ["Pane", "Panino"],
  ["Toast", "Cracker"],
  ["Formaggio", "Burro"],
  ["Panna", "Latte"],
  ["Yogurt", "Kefir"],
  ["Gelato", "Sorbetto"],
  ["Gelato artigianale", "Frozen yogurt"],
  ["Budino", "Crema"],
  ["Marmellata", "Confettura"],
  ["Miele", "Sciroppo"],
  ["Zucchero", "Stevia"],
  ["Sale", "Spezie"],
  ["Pepe", "Paprika"],
  ["Basilico", "Origano"],
  ["Cannella", "Noce moscata"],
  ["Vaniglia", "Mandorla"],
  ["Menta", "Liquirizia"],
  ["Limone", "Lime"],
  ["Arancia", "Pompelmo"],
  ["Mela", "Pera"],
  ["Pesca", "Prugna"],
  ["Ciliegia", "Frutto di bosco"],
  ["Fragola", "Lampone"],
  ["Mirtillo", "Mora"],
  ["Uva", "Uvetta"],
  ["Anguria", "Melone"],
  ["Ananas", "Mango"],
  ["Banana", "Platano"],
  ["Cocco", "Avocado"],
  ["Kiwi", "Frutto della passione"],
  ["Caffè", "Espresso"],
  ["Caffellatte", "Cappuccino"],
  ["Tè", "Matcha"],
  ["Cioccolata calda", "Mocaccino"],
  ["Bibita", "Acqua frizzante"],
  ["Cola", "Birra alla radice"],
  ["Birra", "Sidro"],
  ["Vino", "Spumante"],
  ["Whisky", "Brandy"],
  ["Vodka", "Gin"],
  ["Rum", "Tequila"],
  ["Martini", "Margarita"],
  ["Mojito", "Daiquiri"],
  ["Frullato", "Milkshake"],
  ["Acqua", "Acqua di cocco"],
  ["Brodo", "Fondo"],
  ["Sugo", "Salsa"],
  ["Ketchup", "Senape"],
  ["Maionese", "Aioli"],
  ["Salsa", "Guacamole"],
  ["Crema spalmabile", "Paté"],
  ["Patatine", "Popcorn"],
  ["Pretzel", "Crostoni"],
  ["Mix di frutta secca", "Granola"],
  ["Cereali", "Porridge"],
  ["Barretta", "Barretta proteica"],
  ["Minestra", "Chowder"],
  ["Chili", "Gumbo"],
  ["Paella", "Jambalaya"],
  ["Lasagne", "Cannelloni"],
  ["Ravioli", "Gnocchi"],
  ["Raviolo", "Wonton"],
  ["Involtino primavera", "Involtino"],
  ["Samosa", "Pakora"],
  ["Kebab", "Shawarma"],
  ["Gyros", "Souvlaki"],
  ["Pho", "Banh Mi"],
  ["Pad Thai", "Riso fritto"],
  ["Teriyaki", "Tempura"],
  ["Kimchi", "Crauti"],
  ["Insalata di cavolo", "Coleslaw"],
  ["Caesar", "Cobb"],
  ["Greek salad", "Caprese"],
  ["Bruschetta", "Crostino"],
  ["Fonduta", "Raclette"],
  ["Tagliere", "Antipasto"],
  ["Buffet", "Banchetto"],
  ["Pranzo", "Cena"],
  ["Antipasto", "Portata"],
  ["Dolce", "Pasticceria"],
  ["Caramella", "Gomma"],
  ["Lecca-lecca", "Gomma da masticare"],
  ["Biscotto", "Frollino"],
  ["Macaron", "Éclair"],
  ["Tiramisù", "Cheesecake"],
  ["Cannolo", "Baklava"],
  ["Crêpe", "Crêpe Suzette"],
  ["Fudge", "Toffee"],
  ["Tartufo", "Pralina"],
  ["Marshmallow", "Meringa"],
  ["Panna montata", "Glassa"],
  ["Vegano", "Vegetariano"],
  ["Piccante", "Mite"],
  ["Dolce", "Salato"],
  ["Fritto", "Al forno"],
  ["Fresco", "Surgelato"],
  ["Panetteria", "Gastronomia"],
  ["Asporto", "Consegna"],
  ["Picnic", "Potluck"],
  ["Food truck", "Chiosco"],
  ["Dim sum", "Hot pot"],
  ["Tapas", "Meze"],
  ["Tofu", "Tempeh"],
  ["Salsa di soia", "Tamari"],
  ["Salsa piccante", "Sriracha"],
  ["Olio d'oliva", "Olio di semi"],
  ["Farina", "Farina di mais"],
  ["Marinata", "Salamoia"],
  ["Prosciutto crudo", "Salame"],
  ["Calamari", "Polpo"],
  ["Gazpacho", "Bisque"],
  ["Vongola", "Cozza"],
  ["Scallop", "Abalone"],
  ["Halibut", "Merluzzo"],
  ["Trota", "Persico"],
  ["Anatra", "Oca"],
  ["Agnello", "Montone"],
  ["Cervo", "Bisonte"],
  ["Quaglia", "Fagiano"],
  ["Uovo", "Uovo di quaglia"],
  ["Tuorlo", "Albume"],
  ["Strapazzata", "In camicia"],
  ["Sodo", "Alla coque"],
  ["Frittata", "Quiche"],
  ["Baguette", "Ciabatta"],
  ["Pane a lievitazione naturale", "Segale"],
  ["Pita", "Naan"],
  ["Tortilla", "Wrap"],
  ["Polenta", "Grits"],
  ["Couscous", "Bulgur"],
  ["Orzo", "Miglio"],
  ["Ceci", "Fava"],
  ["Edamame", "Taccola"],
  ["Carciofo", "Asparago"],
  ["Barbabietola", "Ravanello"],
  ["Rapa", "Pastinaca"],
  ["Porro", "Scalogno"],
  ["Cavolo riccio", "Spinacio"],
  ["Rucola", "Lattuga"],
  ["Indivia", "Scarola"],
  ["Finocchio", "Aneto"],
  ["Coriandolo", "Prezzemolo"],
  ["Timo", "Rosmarino"],
  ["Salvia", "Alloro"],
  ["Cardamomo", "Chiodo di garofano"],
  ["Zenzero", "Curcuma"],
  ["Peperoncino", "Jalapeño"],
  ["Habanero", "Serrano"],
  ["Acero", "Agave"],
  ["Melassa", "Treacle"],
  ["Cacao", "Cacao in polvere"],
  ["Chicco di caffè", "Chicco espresso"],
  ["Chai", "Camomilla"],
  ["Tè freddo", "Tè dolce"],
  ["Granita", "Slurpee"],
  ["Punch", "Sangria"],
  ["Vin brulé", "Punch caldo"],
  ["Eggnog", "Toddy"],
  ["Sake", "Soju"],
  ["Mezcal", "Pulque"],
]);
