import { fromTuples } from "./_utils.mjs";

export const pairs = fromTuples([
  ["Guerre Stellari", "Star Trek"],
  ["Batman", "Superman"],
  ["Marvel", "DC"],
  ["Harry Potter", "Il Signore degli Anelli"],
  ["Friends", "Seinfeld"],
  ["Il Trono di Spade", "House of the Dragon"],
  ["Breaking Bad", "Better Call Saul"],
  ["The Office", "Parks and Recreation"],
  ["Stranger Things", "Dark"],
  ["James Bond", "Mission Impossible"],
  ["Indiana Jones", "Tomb Raider"],
  ["Jurassic Park", "King Kong"],
  ["Titanic", "Avatar"],
  ["Forrest Gump", "Cast Away"],
  ["Il Padrino", "Scarface"],
  ["Pulp Fiction", "Reservoir Dogs"],
  ["Inception", "Interstellar"],
  ["Matrix", "Blade Runner"],
  ["Lo Squalo", "Alien"],
  ["Rocky", "Rambo"],
  ["Terminator", "RoboCop"],
  ["Ritorno al Futuro", "Ghostbusters"],
  ["Mamma ho perso l'aereo", "Die Hard"],
  ["Shrek", "Monsters and Co"],
  ["Frozen", "Oceania"],
  ["Il Re Leone", "Tarzan"],
  ["Alla ricerca di Nemo", "Alla ricerca di Dory"],
  ["Toy Story", "Cars"],
  ["Spider-Man", "Iron Man"],
  ["Captain America", "Thor"],
  ["Avengers", "Justice League"],
  ["X-Men", "Fantastici Quattro"],
  ["Fast and Furious", "Need for Speed"],
  ["Transformers", "Pacific Rim"],
  ["Pirati dei Caraibi", "L'isola del tesoro"],
  ["Twilight", "Hunger Games"],
  ["Il Signore degli Anelli", "Lo Hobbit"],
  ["Sherlock Holmes", "Poirot"],
  ["Doctor Who", "Star Trek"],
  ["Grey's Anatomy", "Dr House"],
  ["Lost", "Survivor"],
  ["Il Cavaliere Oscuro", "Batman Begins"],
  ["Gladiatore", "Braveheart"],
  ["Titanic", "Notebook"],
  ["La La Land", "Greatest Showman"],
  ["Oppenheimer", "Barbie"],
  ["Dune", "Guerre Stellari"],
  ["Top Gun", "Top Gun Maverick"],
  ["Black Panther", "Wonder Woman"],
  ["Deadpool", "Wolverine"],
  ["Men in Black", "Ghostbusters"],
  ["The Walking Dead", "Fear the Walking Dead"],
  ["Squid Game", "Alice in Borderland"],
  ["Wednesday", "Famiglia Addams"],
  ["Peaky Blinders", "Boardwalk Empire"],
  ["La Casa di Carta", "Ocean's Eleven"],
  ["The Crown", "Downton Abbey"],
  ["Bridgerton", "Gossip Girl"],
  ["Euphoria", "Skins"],
  ["Westworld", "Black Mirror"],
  ["True Detective", "Mindhunter"],
  ["Narcos", "Breaking Bad"],
  ["The Witcher", "Il Trono di Spade"],
  ["Vichinghi", "Il Trono di Spade"],
  ["Casino", "Quei Bravi Ragazzi"],
  ["Scarface", "Carlito's Way"],
  ["Le Ali della Libertà", "The Green Mile"],
  ["Fight Club", "American Psycho"],
  ["Iron Man", "Captain America"],
  ["Guardians of the Galaxy", "Thor"],
  ["Ant-Man", "Wasp"],
  ["Doctor Strange", "Scarlet Witch"],
  ["Black Widow", "Hawkeye"],
  ["Loki", "Thor"],
  ["WandaVision", "Agatha"],
  ["Mandalorian", "Boba Fett"],
  ["Obi-Wan", "Anakin"],
  ["Luke Skywalker", "Darth Vader"],
  ["Han Solo", "Chewbacca"],
  ["Yoda", "Obi-Wan"],
  ["Frodo", "Sam"],
  ["Gandalf", "Dumbledore"],
  ["Hermione", "Ron"],
  ["Snape", "Dumbledore"],
  ["Voldemort", "Sauron"],
  ["Gollum", "Yoda"],
  ["Legolas", "Aragorn"],
  ["Gimli", "Legolas"],
  ["Neo", "Morpheus"],
  ["Trinity", "Neo"],
  ["Agent Smith", "Neo"],
  ["John Wick", "Jason Bourne"],
  ["Taken", "John Wick"],
  ["Mad Max", "Blade Runner"],
  ["Alien", "Predator"],
  ["King Kong", "Godzilla"],
  ["Godzilla", "Mothra"],
  ["Jurassic World", "Jurassic Park"],
  ["ET", "Close Encounters"],
  ["Cast Away", "Robinson Crusoe"],
  ["Cast Away", "Forrest Gump"],
  ["Cinema Paradiso", "La vita è bella"],
  ["Il Gladiatore", "Troy"],
  ["Interstellar", "Arrival"],
  ["Il Miglio Verde", "Le Ali della Libertà"],
  ["Il Silenzio degli Innocenti", "Seven"],
  ["Kill Bill", "Pulp Fiction"],
  ["Django", "Kill Bill"],
  ["C'era una volta a Hollywood", "Pulp Fiction"],
  ["Il Grande Lebowski", "Fargo"],
  ["No Country", "Fargo"],
]);
