import { fromTuples } from "./_utils.mjs";

export const pairs = fromTuples([
  ["Parigi", "Londra"],
  ["Museo", "Galleria"],
  ["Hotel", "Ostello"],
  ["Foresta", "Parco"],
  ["Aeroporto", "Stazione"],
  ["Biblioteca", "Libreria"],
  ["Roma", "Atene"],
  ["Berlino", "Vienna"],
  ["Madrid", "Lisbona"],
  ["Amsterdam", "Bruxelles"],
  ["Praga", "Budapest"],
  ["Dublino", "Edimburgo"],
  ["Stoccolma", "Oslo"],
  ["Copenaghen", "Helsinki"],
  ["Milano", "Torino"],
  ["Barcellona", "Valencia"],
  ["Napoli", "Firenze"],
  ["Venezia", "Verona"],
  ["New York", "Chicago"],
  ["Los Angeles", "San Francisco"],
  ["Miami", "Orlando"],
  ["Boston", "Filadelfia"],
  ["Seattle", "Portland"],
  ["Toronto", "Montreal"],
  ["Città del Messico", "Guadalajara"],
  ["Buenos Aires", "Santiago"],
  ["Rio", "San Paolo"],
  ["Il Cairo", "Marrakech"],
  ["Dubai", "Abu Dhabi"],
  ["Istanbul", "Ankara"],
  ["Tokyo", "Osaka"],
  ["Seul", "Busan"],
  ["Pechino", "Shanghai"],
  ["Bangkok", "Singapore"],
  ["Sydney", "Melbourne"],
  ["Mumbai", "Delhi"],
  ["Scuola", "Università"],
  ["Ospedale", "Clinica"],
  ["Banca", "Bancomat"],
  ["Ufficio", "Coworking"],
  ["Fabbrica", "Magazzino"],
  ["Fattoria", "Ranch"],
  ["Mercato", "Centro commerciale"],
  ["Ristorante", "Caffè"],
  ["Bar", "Pub"],
  ["Teatro", "Cinema"],
  ["Stadio", "Arena"],
  ["Zoo", "Acquario"],
  ["Castello", "Palazzo"],
  ["Cattedrale", "Cappella"],
  ["Tempio", "Santuario"],
  ["Moschea", "Sinagoga"],
  ["Cimitero", "Memoriale"],
  ["Ponte", "Galleria"],
  ["Porto", "Marina"],
  ["Molo", "Banchina"],
  ["Spiaggia", "Resort"],
  ["Isola", "Costa"],
  ["Montagna", "Valle"],
  ["Deserto", "Oasi"],
  ["Lago", "Fiume"],
  ["Cascata", "Sorgente"],
  ["Grotta", "Caverna"],
  ["Villaggio", "Paese"],
  ["Città", "Capitale"],
  ["Ambasciata", "Consolato"],
  ["Tribunale", "Municipio"],
  ["Questura", "Caserma dei pompieri"],
  ["Prigione", "Carcere"],
  ["Fermata autobus", "Stazione ferroviaria"],
  ["Metro", "Tram"],
  ["Parcheggio", "Garage"],
  ["Autostrada", "Superstrada"],
  ["Piazza", "Largo"],
  ["Viale", "Boulevard"],
  ["Cucina", "Sala da pranzo"],
  ["Camera", "Soggiorno"],
  ["Bagno", "Lavanderia"],
  ["Soffitta", "Cantina"],
  ["Atrio", "Corridoio"],
  ["Appartamento", "Condominio"],
  ["Cottage", "Baita"],
  ["Villa", "Mansione"],
  ["Locanda", "Motel"],
  ["Resort", "Rifugio"],
  ["Parco divertimenti", "Luna park"],
  ["Centro congressi", "Fiera"],
  ["Laboratorio", "Centro ricerche"],
  ["Osservatorio", "Planetario"],
  ["Miniera", "Cava"],
  ["Centrale elettrica", "Sottostazione"],
  ["Diga", "Bacino"],
  ["Grattacielo", "Torre"],
  ["Boutique", "Grande magazzino"],
  ["Parrucchiere", "Barbiere"],
  ["Palestra", "Centro fitness"],
  ["Campo da golf", "Country club"],
  ["Pista di ghiaccio", "Bowling"],
  ["Parco nazionale", "Parco regionale"],
  ["Penisola", "Capo"],
  ["Baia", "Golfo"],
  ["Centro storico", "Downtown"],
  ["Chinatown", "Little Italy"],
  ["Distributore", "Colonnina elettrica"],
  ["Ufficio postale", "Corriere"],
  ["Data center", "Server farm"],
  ["Ritiro bagagli", "Controllo sicurezza"],
  ["Pista", "Hangar"],
  ["Traghetto", "Terminal crociere"],
  ["Parlamento", "Congresso"],
  ["Studio TV", "Radio"],
  ["Laboratorio scienze", "Aula informatica"],
  ["Pronto soccorso", "Guardia medica"],
  ["Clinica veterinaria", "Ospedale animali"],
  ["Stalla", "Fienile"],
  ["Serra", "Vivaio"],
  ["Fermata metro", "Terminal bus"],
  ["Stazione sciistica", "Rifugio montano"],
  ["Ufficio turistico", "Info point"],
  ["Piramide", "Tempio"],
  ["Colosseo", "Foro"],
  ["Tour Eiffel", "Big Ben"],
  ["Grande Muraglia", "Città Proibita"],
  ["Taj Mahal", "Forte Rosso"],
  ["Stonehenge", "Vallo di Adriano"],
  ["Louvre", "Ermitage"],
  ["Broadway", "West End"],
  ["Wall Street", "City"],
  ["Times Square", "Piccadilly"],
  ["Central Park", "Hyde Park"],
  ["Grand Canyon", "Death Valley"],
  ["Cascate del Niagara", "Cascate Vittoria"],
  ["Everest", "K2"],
  ["Alpi", "Pirenei"],
  ["Sahara", "Gobi"],
  ["Amazzonia", "Congo"],
  ["Tamigi", "Senna"],
  ["Mediterraneo", "Caraibi"],
  ["Pacifico", "Atlantico"],
  ["Hawaii", "Bahamas"],
  ["Santorini", "Mykonos"],
  ["Ibiza", "Maiorca"],
  ["Cannes", "Nizza"],
  ["Monaco", "Monte Carlo"],
  ["Las Vegas", "Atlantic City"],
  ["Disneyland", "Universal Studios"],
  ["Oktoberfest", "Carnevale"],
  ["Mercatino", "Mercato contadino"],
  ["Outlet", "Centro commerciale"],
  ["Campeggio", "Area caravan"],
  ["Sentiero", "Pista ciclabile"],
  ["Riserva naturale", "Oasi ornitologica"],
  ["Città fantasma", "Centro storico"],
  ["Lungomare", "Porto antico"],
  ["Quartiere finanziario", "Quartiere delle arti"],
  ["Dogana", "Posto di blocco"],
  ["Borsa", "Sala contrattazioni"],
  ["Casa Bianca", "Cremlino"],
  ["Buckingham Palace", "Versailles"],
  ["Centro spaziale", "Piattaforma di lancio"],
  ["Orto botanico", "Arboreto"],
  ["Vigneto", "Cantina"],
  ["Birrificio", "Distilleria"],
  ["Mercato gastronomico", "Mercato notturno"],
  ["Rooftop bar", "Speakeasy"],
  ["Area cani", "Spiaggia per cani"],
  ["Parco acquatico", "Splash park"],
  ["Barriera corallina", "Punto immersioni"],
  ["Piscina pubblica", "Vasca nuoto"],
  ["Onsen", "Terme pubbliche"],
  ["Cambio valuta", "Agenzia viaggi"],
  ["Concierge", "Reception"],
  ["Attico", "Suite junior"],
  ["Uscita emergenza", "Scale antincendio"],
  ["Ormeggio", "Rampa barche"],
  ["Faro", "Stazione nebbia"],
  ["Parco eolico", "Parco solare"],
  ["Rifugio alpino", "Bivacco"],
  ["Hotel di ghiaccio", "Igloo"],
  ["Capsule hotel", "Pod hotel"],
  ["Casinò", "Sala poker"],
  ["Comic Con", "Fiera dei videogiochi"],
  ["Cappella matrimoniale", "Anagrafe"],
  ["Sala banchetti", "Sala ricevimenti"],
  ["Casa funeraria", "Crematorio"],
  ["Muro dei ricordi", "Monumento"],
  ["Scuola guida", "Scuola volo"],
  ["Centro immersioni", "Scuola surf"],
  ["Agriturismo", "Farm stay"],
  ["Risaia terrazzata", "Piantagione tè"],
  ["Sentiero costiero", "Lungomare"],
  ["Lungomare", "Passeggiata"],
  ["Molo", "Pontile"],
  ["Funivia", "Cabina"],
  ["Eliporto", "Idroscalo"],
  ["Duty free", "Negozio viaggi"],
  ["Gate", "Terminal"],
  ["Torre di controllo", "Radar"],
  ["Terminal cargo", "Cantiere merci"],
  ["Base navale", "Base aerea"],
]);
